### ISSUE TITLE
Doesn't compile with gcc-4.8.5

### ISSUE THREAD

**Issue by jpeirce** [pok3r-custom/pok3rtool#1]
Trying to compile this on GCC 4.8.5 and it fails during make:
cc1plus: error: -Werror=delete-incomplete: no option -Wdelete-incomplete

Looks like this flag was added in GCC 4.9. 

Forcing it to compile with 5.3.1 did work fine.

**Comment by jpeirce** [comment]
Thanks for fixing this! Can confirm it works now after your latest commit.

**Comment by ChaoticEnigma** [comment]
Oops, sorry I never said anything here. Thanks for pointing this out. I usually build with latest GCC, but 4.8 should be supported if the only incompatibility is warning options.
