### ISSUE TITLE
cannot compile on Linux

### ISSUE THREAD

**Issue by FbN** [pok3r-custom/pok3rtool#17]
Tested with different gcc version (9, 12)

Erorror:

libchaos/chaos/base/zerror.cpp:800:20: error: variable length array declaration cannot have 'static' storage duration
    static uint8_t alternate_stack[SIGSTKSZ];
                   ^               ~~~~~~~~

**Comment by hansemro** [comment]
There is a one line change to fix this in libchaos: https://github.com/ChaoticEnigma/libchaos/pull/5

**Comment by FbN** [comment]
I confirm this solve the problem. Thank you @hansemro
