### ISSUE TITLE
git submodule init asking for authentication

### ISSUE THREAD

**Issue by jpeirce** [pok3r-custom/pok3rtool#2]
First is if I enter blank username/password, second is if I cancel the login prompt.

jack@linux:~/src/pok3rtool> git submodule update --init
git submodule update --init
Submodule 'libchaos' (https://gitlab.com/ChaoticEnigma/libchaos.git) registered for path 'libchaos'
Cloning into '/home/jack/src/pok3rtool/libchaos'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/ChaoticEnigma/libchaos.git/'
fatal: clone of 'https://gitlab.com/ChaoticEnigma/libchaos.git' into submodule path '/home/jack/src/pok3rtool/libchaos' failed
Failed to clone 'libchaos'. Retry scheduled
Cloning into '/home/jack/src/pok3rtool/libchaos'...
remote: HTTP Basic: Access denied
fatal: Authentication failed for 'https://gitlab.com/ChaoticEnigma/libchaos.git/'
fatal: clone of 'https://gitlab.com/ChaoticEnigma/libchaos.git' into submodule path '/home/jack/src/pok3rtool/libchaos' failed
Failed to clone 'libchaos' a second time, aborting

jack@linux:~/src/pok3rtool> git submodule update --init
Cloning into '/home/jack/src/pok3rtool/libchaos'...
error: unable to read askpass response from '/usr/lib/ssh/ssh-askpass'
Username for 'https://gitlab.com': ^C

**Comment by ChaoticEnigma** [comment]
I'm aware of this issue, it seems to be a long standing but difficult to reproduce bug in GitLab. My gitlab ci is failing for the same reason. Looking into it.

**Comment by jpeirce** [comment]
I'm shooting from the hip, and you've probably already seen it, but from the gitlab docs:
![screenshot-2018-6-18 gitlab and ssh keys gitlab](https://user-images.githubusercontent.com/22495/41553939-7a1f943e-72f0-11e8-967f-2270c969144e.png)

**Comment by ChaoticEnigma** [comment]
The issue is that anonymous HTTPS is not working correctly. According to the docs, public repositories should not prompt for a username on HTTPS read access. Reports of this go back years, but reproducing it is seemingly inconsistent. One comment on an issue suggested it happens on repositories that were created private and made public (imported repositories are always imported as private). It may be that I have to recreate my repositories as public.

**Comment by jpeirce** [comment]
Just leaving these here in case you haven't seen them:
https://gitlab.com/gitlab-org/gitlab-ce/issues/33150
https://gitlab.com/gitlab-org/gitlab-ce/issues/24032

**Comment by ChaoticEnigma** [comment]
Alright, this seems to be fixed. I suspect it wasn't a bug, just some misconfiguration on my part. It looks like all the gitlab repos can be cloned anonymously now.
